services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile.api
    container_name: todo-api
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    command: ["npm", "run", "start:dev", "start:prod"]
    depends_on:
      - postgres
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

  postgres:
    image: postgres:latest
    container_name: todo-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: